model_cfg:
  type: "TransformerStateEstV3Model"
  num_groups: 64
  group_size: 16
  in_channels: 6
  out_channels: 3
  num_layers: 6
  attention_head_dim: 72
  patchified_input: true
  num_in_frames: 2
  num_out_frames: 1
  patch_file: /home/cjimenez/projects/TrackAnyCloth/UniClothDiff/assets/trtm_441_voronoi_template.pkl

diffusion_cfg:
  type: "DDPM_StateEst"
  num_train_timesteps: 1000
  beta_schedule: "scaled_linear"
  shape_loss_weight: 1.829e-03

wandb_cfg:
  project_name: "UniClothDiff_TRTM"
  exp_name: "ablation_diff_sw1.829e-03"

dataset_cfg:
  type: "TRTMDiffusionDataset"
  data_dir: "/home/cjimenez/projects/datasets/TRTM/template_square"
  train_mode: "full"
  num_sample_points: 400
  do_point_cloud_augmentation: true
  points_jitter_sigma: 0.002
  points_drop_ratio: 0.0
